---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      labels:
        app: worker
    spec:
      containers:
       - name: worker
         image: mirmika/worker:${IMAGE_TAG}
         env:
         - name: REDIS_HOST
           value: redis-service
         - name: DB_HOST
           value: pg-service
         - name: DB_USERNAME
           value: "postgres"
         - name: DB_PASSWORD
           value: "postgres"
         - name: DB_NAME
           value: "votes"
         - name: DB_PORT
           value: "5432"  
---
apiVersion: v1
kind: Service
metadata:
  name: worker-service
spec:
  selector:
    app: worker
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80         
