name: Build and Deploy to EKS

on:
  push:
    branches:
      - main
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    
    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v4
        
      # Log into Docker
      - name: Log in to Docker
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Check directory structure
        run: |
          ls -R ./ironhack-project-1 
          
      # Step 3: Build Docker images
      - name: Build image for result service
        run: |
          cd ./ironhack-project-1/result
          sudo docker build -t your-dockerhub-username/result:${GITHUB_REF##*/} .
      - name: Build image for vote service
        run: |
          cd ./ironhack-project-1/vote
          sudo docker build -t your-dockerhub-username/vote:${GITHUB_REF##*/} .

      - name: Build image for worker service
        run: |
          cd ./ironhack-project-1/worker
          sudo docker build -t your-dockerhub-username/worker:${GITHUB_REF##*/} .

      # Configure AWS Credentials
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      # Install kubectl
      - name: Install kubectl
        run: |
         curl -LO "https://dl.k8s.io/release/v1.24.0/bin/linux/amd64/kubectl"
         chmod +x ./kubectl
         sudo mv ./kubectl /usr/local/bin/kubectl


      # Deploy to EKS
      - name: Deploy to EKS
        run: |
           kubectl apply -f ingress.yaml
           kubectl apply -f vote.yaml
           kubectl apply -f result.yaml
           kubectl apply -f redis.yaml
           kubectl apply -f worker.yaml
           kubectl apply -f postgres.yaml
